/tf_static:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local

/camera/camera/infra1/image_rect_raw:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile

/camera/camera/infra2/image_rect_raw:
  history: keep_last
  depth: 10
  reliability: best_effort
  durability: volatile

/camera/camera/imu:
  history: keep_last
  depth: 100
  reliability: best_effort
  durability: volatile

/camera/camera/accel/sample:
  history: keep_last
  depth: 100
  reliability: best_effort
  durability: volatile

/camera/camera/gyro/sample:
  history: keep_last
  depth: 100
  reliability: best_effort
  durability: volatile

